Completed prep-javascript-variables exercise. - Rosemary Liu
rosemary-liu/prep-0122-code-solutions pull request #12
Opened 2022-01-17 05:33 UTC by rosemary-liu

![image](https://user-images.githubusercontent.com/95596680/149713302-7826001f-209b-4345-8fa2-6240705cf8e6.png)

2022-01-17 14:59 UTC, thebearingedge requested changes

2022-01-17 14:59 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    var nothing = 'null';
For numbers, booleans, and `null`, you should leave out the quotes, because otherwise JavaScript sees a string.

2022-01-17 21:21 UTC, thebearingedge requested changes

2022-01-17 21:21 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    console.log('value of likesVegetables:', likesVegetables);
We can remove the quotes for the number and boolean here too 👍

2022-01-18 02:47 UTC, rosemary-liu commented on prep-javascript-variables/index.html
> +    console.log('value of likesVegetables:', likesVegetables);
Had to force push since my VS Code did not contain the changes that I previously made in GitHub and it gave me the error "fatal: Not possible to fast-forward, aborting." 

Let me know if I need to do this differently.

2022-01-18 16:07 UTC, thebearingedge approved these changes

2022-01-18 16:08 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    console.log('value of likesVegetables:', likesVegetables);
That's fine this time, I believe this was due to the change made on the GitHub website instead of in VS Code. Just beware that force pushing can delete prior work if you're not careful. But tbh I probably would have force pushed in this specific case 😂

2022-01-18 16:19 UTC, merged